In [8]:
import pandas as pd

data = pd.read_csv("mental_health.csv")
texts = data["text"].astype(str).tolist()
labels = data["label"].values

In [ ]:
tokenizer = Tokenizer(num_words=5000, oov_token="<OOV>")
tokenizer.fit_on_texts(texts)
sequences = tokenizer.texts_to_sequences(texts)
padded_sequences = pad_sequences(sequences, padding='post', maxlen=50)

print(padded_sequences)

[[2201  912 1714 ...    0    0    0]
 [  53  165  580 ...    0    0    0]
 [1624 3185    1 ... 3869  735    1]
 ...
 [  16    8  547 ...    0    0    0]
 [  73  592    3 ...    1    4   58]
 [  34 3242   86 ...    0    0    0]]


In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

tokenizer = Tokenizer(num_words=5000, oov_token="<OOV>")
tokenizer.fit_on_texts(texts)
sequences = tokenizer.texts_to_sequences(texts)
padded_sequences = pad_sequences(sequences, padding='post', maxlen=50)

X_train, X_test, y_train, y_test = train_test_split(padded_sequences, labels, test_size=0.2, random_state=42)

model = tf.keras.Sequential([
    tf.keras.layers.Embedding(5000, 16, input_length=50),
    tf.keras.layers.GlobalAveragePooling1D(),
    tf.keras.layers.Dense(16, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=100, validation_data=(X_test, y_test), verbose=1)

Epoch 1/100


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


700/700 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.7692 - loss: 0.5210 - val_accuracy: 0.8890 - val_loss: 0.2853
Epoch 2/100
700/700 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.9031 - loss: 0.2565 - val_accuracy: 0.9064 - val_loss: 0.2352
Epoch 3/100
700/700 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9173 - loss: 0.2081 - val_accuracy: 0.9044 - val_loss: 0.2319
Epoch 4/100
700/700 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.9284 - loss: 0.1906 - val_accuracy: 0.9133 - val_loss: 0.2301
Epoch 5/100
700/700 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.9384 - loss: 0.1631 - val_accuracy: 0.8999 - val_loss: 0.2479
Epoch 6/100
700/700 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.9384 - loss: 0.1607 - val_accuracy: 0.9130 - val_loss: 0.2362
Epoch 7/100
700/700 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.9441 - loss: 0.1521 - val_accuracy: 0.9117 - val_loss: 0.2452
Epoch 8/100
700/700 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9473 - loss: 0.1432 - val_accuracy: 0.9042

In [ ]:
def predict_text(text):
    seq = tokenizer.texts_to_sequences([text])
    padded = pad_sequences(seq, padding='post', maxlen=50)
    prediction = model.predict(padded)
    return int(prediction[0] > 0.5)

user_input = input("Enter a sentence: ")
prediction = predict_text(user_input)
print("Predicted Label:", prediction)

Enter a sentence: hello ill kill you
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
Predicted Label: 1


<ipython-input-18-a156a6413dda>:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return int(prediction[0] > 0.5)


In [20]:
model.save("Mental_Health.keras")


In [21]:
from google.colab import files
files.download("Mental_Health.keras")  # Change filename accordingly

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>